INSERT INTO c_congresso.estados(uf,nome_estado,regiao)
VALUES
  ('AC','Acre','Norte'),
  ('AL','Alagoas','Nordeste'),
  ('AM','Amazonas','Norte'),
  ('AP','Amapá','Norte'),
  ('BA','Bahia','Nordeste'),
  ('CE','Ceará','Nordeste'),
  ('DF','Distrito Federal','Centro-Oeste'),
  ('ES','Espírito Santo','Sudeste'),
  ('GO','Goiás','Centro-Oeste'),
  ('MA','Maranhão','Nordeste'),
  ('MG','Minas Gerais','Sudeste'),
  ('MT','Mato Grosso','Centro-Oeste'),
  ('MS','Mato Grosso do Sul','Centro-Oeste'),
  ('PA','Pará','Norte'),
  ('PB','Paraíba','Nordeste'),
  ('PR','Paraná','Sul'),
  ('PE','Pernambuco','Nordeste'),
  ('PI','Piauí','Nordeste'),
  ('RJ','Rio de Janeiro','Sudeste'),
  ('RN','Rio Grande do Norte','Nordeste'),
  ('RS','Rio Grande do Sul','Sul'),
  ('RR','Roraima','Norte'),
  ('RO','Rondônia','Norte'),
  ('SC','Santa Catarina','Sul'),
  ('SP','São Paulo','Sudeste'),
  ('SE','Sergipe','Nordeste'),
  ('TO','Tocantins','Norte')
;