#./amazon-fgv.sh capture.camdep_capture_log
#./amazon-fgv.sh capture.camdep_deputados_atual
#./amazon-fgv.sh capture.camdep_deputados_detalhes
#./amazon-fgv.sh capture.camdep_deputados_detalhes_comissoes
./amazon-fgv.sh capture.camdep_deputados_detalhes_comissoes_cargos
./amazon-fgv.sh capture.camdep_deputados_detalhes_filiacoes
./amazon-fgv.sh capture.camdep_deputados_detalhes_lideranca
./amazon-fgv.sh capture.camdep_deputados_detalhes_periodos_exercicio
./amazon-fgv.sh capture.camdep_deputados_historico
./amazon-fgv.sh capture.camdep_discursos_lista
./amazon-fgv.sh capture.camdep_partidos
./amazon-fgv.sh capture.camdep_proposicoes_id
./amazon-fgv.sh capture.camdep_proposicoes_periodo
./amazon-fgv.sh capture.camdep_proposicoes_plenario_ano
./amazon-fgv.sh capture.camdep_proposicoes_siglas
./amazon-fgv.sh capture.camdep_proposicoes_votacao
./amazon-fgv.sh capture.camdep_proposicoes_votacao_bancada
./amazon-fgv.sh capture.camdep_proposicoes_votacao_deputado
./amazon-fgv.sh r_camdep.gr_votacao_deputados_all
./amazon-fgv.sh r_camdep.gr_votacao_deputados_ano
./amazon-fgv.sh r_camdep.json_votacao_deputados
./amazon-fgv.sh a_camdep.cm_votacao_deputados
./amazon-fgv.sh a_camdep.deputados
./amazon-fgv.sh a_camdep.deputados_contatos
./amazon-fgv.sh a_camdep.deputados_detalhes
./amazon-fgv.sh a_camdep.deputados_legislaturas
